/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package payroll.management.system;

import java.sql.*;
//To make the java option work
import javax.swing.JOptionPane;

/**
 *
 * @author HP Elitebook 840 G8
 */
public class EmployeeManagement extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeManagement
     */
    public EmployeeManagement() {
        initComponents();
        setLocationRelativeTo(null); //To center
        connect(); // Calling database connection code
    }

    // Global variables for database connection
    Connection con;
    PreparedStatement pst;
    ResultSet rs;

    public void connect() // method
    {
        // Database connection
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/payroll_system", "root", "");
            JOptionPane.showMessageDialog(null, "Connection Done");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No Connection");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        ManageEmployeesBTN = new javax.swing.JButton();
        SalaryCalculationBTN = new javax.swing.JButton();
        PayslipManagementBTN = new javax.swing.JButton();
        PayrollReportsBTN = new javax.swing.JButton();
        LogoutBTN = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        EmployeeIDCMB = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        EmployeeNameTXT = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        JobRoleTXT = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        DepartmentTXT = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        BasicSalaryTXT = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        AllowanceTXT = new javax.swing.JTextField();
        InsertBTN = new javax.swing.JButton();
        UpdateBTN = new javax.swing.JButton();
        DeleteBTN = new javax.swing.JButton();
        SearchBTN = new javax.swing.JButton();
        ClearBTN = new javax.swing.JButton();
        BackBTN = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(0, 128, 0));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Main Menu");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(316, 316, 316))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 222));

        ManageEmployeesBTN.setBackground(new java.awt.Color(0, 153, 0));
        ManageEmployeesBTN.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        ManageEmployeesBTN.setText("Manage Employees");
        ManageEmployeesBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageEmployeesBTNActionPerformed(evt);
            }
        });

        SalaryCalculationBTN.setBackground(new java.awt.Color(0, 153, 0));
        SalaryCalculationBTN.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        SalaryCalculationBTN.setText("Salary Calculation");
        SalaryCalculationBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalaryCalculationBTNActionPerformed(evt);
            }
        });

        PayslipManagementBTN.setBackground(new java.awt.Color(0, 153, 0));
        PayslipManagementBTN.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        PayslipManagementBTN.setText("Payslip Management");
        PayslipManagementBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayslipManagementBTNActionPerformed(evt);
            }
        });

        PayrollReportsBTN.setBackground(new java.awt.Color(0, 153, 0));
        PayrollReportsBTN.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        PayrollReportsBTN.setText("Payroll Reports");
        PayrollReportsBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayrollReportsBTNActionPerformed(evt);
            }
        });

        LogoutBTN.setBackground(new java.awt.Color(0, 153, 0));
        LogoutBTN.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        LogoutBTN.setText("Logout");
        LogoutBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(PayrollReportsBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ManageEmployeesBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(SalaryCalculationBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(PayslipManagementBTN))
                    .addComponent(LogoutBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ManageEmployeesBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SalaryCalculationBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PayslipManagementBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PayrollReportsBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LogoutBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(0, 128, 0));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Employee Management");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(275, 275, 275))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(204, 255, 222));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel5.setText("Select Employee ID");

        EmployeeIDCMB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel6.setText("Employee Name");

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel7.setText("Job Role");

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel8.setText("Department");

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel9.setText("Basic Salary");

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel10.setText("Allowance");

        InsertBTN.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        InsertBTN.setForeground(new java.awt.Color(0, 153, 51));
        InsertBTN.setText("Insert");
        InsertBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertBTNActionPerformed(evt);
            }
        });

        UpdateBTN.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        UpdateBTN.setForeground(new java.awt.Color(0, 153, 51));
        UpdateBTN.setText("Update");
        UpdateBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBTNActionPerformed(evt);
            }
        });

        DeleteBTN.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        DeleteBTN.setForeground(new java.awt.Color(0, 153, 51));
        DeleteBTN.setText("Delete");
        DeleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBTNActionPerformed(evt);
            }
        });

        SearchBTN.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        SearchBTN.setForeground(new java.awt.Color(0, 153, 51));
        SearchBTN.setText("Search");
        SearchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBTNActionPerformed(evt);
            }
        });

        ClearBTN.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        ClearBTN.setForeground(new java.awt.Color(0, 153, 51));
        ClearBTN.setText("Clear");
        ClearBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBTNActionPerformed(evt);
            }
        });

        BackBTN.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        BackBTN.setForeground(new java.awt.Color(204, 51, 0));
        BackBTN.setText("Back");
        BackBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(187, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AllowanceTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BasicSalaryTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DepartmentTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JobRoleTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(EmployeeIDCMB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EmployeeNameTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(131, 131, 131)
                        .addComponent(BackBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(InsertBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UpdateBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DeleteBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SearchBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ClearBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(177, 177, 177))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(EmployeeIDCMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BackBTN)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(EmployeeNameTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(JobRoleTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(DepartmentTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(BasicSalaryTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(AllowanceTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InsertBTN)
                    .addComponent(UpdateBTN)
                    .addComponent(DeleteBTN)
                    .addComponent(SearchBTN)
                    .addComponent(ClearBTN))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ManageEmployeesBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageEmployeesBTNActionPerformed

        // To open employee management page
        EmployeeManagement Main = new EmployeeManagement();
        Main.setVisible(true);
    }//GEN-LAST:event_ManageEmployeesBTNActionPerformed

    private void SalaryCalculationBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalaryCalculationBTNActionPerformed

        // To open salary calculation page
        SalaryCalculation Main = new SalaryCalculation();
        Main.setVisible(true);
    }//GEN-LAST:event_SalaryCalculationBTNActionPerformed

    private void PayslipManagementBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayslipManagementBTNActionPerformed

        // To open payslip management page
        PayslipManagement Main = new PayslipManagement();
        Main.setVisible(true);
    }//GEN-LAST:event_PayslipManagementBTNActionPerformed

    private void PayrollReportsBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayrollReportsBTNActionPerformed

        // To open payroll reports page
        PayrollReports Main = new PayrollReports();
        Main.setVisible(true);
    }//GEN-LAST:event_PayrollReportsBTNActionPerformed

    private void LogoutBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBTNActionPerformed

        // Logout button code
        JOptionPane.showMessageDialog(this, "Logout Successful", "Logout", JOptionPane.INFORMATION_MESSAGE);

        // To close main menu page
        this.hide();

        // To open login page again
        LoginPage Main = new LoginPage();
        Main.setVisible(true);

    }//GEN-LAST:event_LogoutBTNActionPerformed

    private void InsertBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertBTNActionPerformed

        try {
            String employeeName = EmployeeNameTXT.getText();
            String jobRole = JobRoleTXT.getText();
            String department = DepartmentTXT.getText();
            int basicSalary = Integer.parseInt(BasicSalaryTXT.getText());
            int allowance = Integer.parseInt(AllowanceTXT.getText());

            pst = con.prepareStatement("INSERT INTO employee_details (Employee_Name, Job_Role, Department, Basic_Salary, Allowance) VALUES (?,?,?,?,?)");

            pst.setString(1, employeeName);
            pst.setString(2, jobRole);
            pst.setString(3, department);
            pst.setInt(4, basicSalary);
            pst.setInt(5, allowance);

            int K = pst.executeUpdate();

            if (K == 1) {
                JOptionPane.showMessageDialog(null, "Insertion Success");

                EmployeeNameTXT.setText("");
                JobRoleTXT.setText("");
                DepartmentTXT.setText("");
                BasicSalaryTXT.setText("");
                AllowanceTXT.setText("");

                EmployeeNameTXT.requestFocus(); // Cursor blinks
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Insertion Not Successfull");
        }

    }//GEN-LAST:event_InsertBTNActionPerformed

    private void UpdateBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBTNActionPerformed

        try {
            String employeeName = EmployeeNameTXT.getText();
            String jobRole = JobRoleTXT.getText();
            String department = DepartmentTXT.getText();
            int basicSalary = Integer.parseInt(BasicSalaryTXT.getText());
            int allowance = Integer.parseInt(AllowanceTXT.getText());
            int id = Integer.parseInt(EmployeeIDCMB.getSelectedItem().toString());

            pst = con.prepareStatement("UPDATE employee_details SET Employee_Name=?, Job_Role=?, Department=?, Basic_Salary=?, Allowance=? WHERE ID=?");

            pst.setString(1, employeeName);
            pst.setString(2, jobRole);
            pst.setString(3, department);
            pst.setInt(4, basicSalary);
            pst.setInt(5, allowance);
            pst.setInt(6, id);

            int K = pst.executeUpdate();

            if (K == 1) {
                JOptionPane.showMessageDialog(this, "Record Updated");

                EmployeeNameTXT.setText("");
                JobRoleTXT.setText("");
                DepartmentTXT.setText("");
                BasicSalaryTXT.setText("");
                AllowanceTXT.setText("");

                EmployeeNameTXT.requestFocus();
            } else {
                JOptionPane.showMessageDialog(this, "Record Not Updated");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Update Not Successfull");
        }

    }//GEN-LAST:event_UpdateBTNActionPerformed

    private void DeleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBTNActionPerformed

        try {
            int id = Integer.parseInt(EmployeeIDCMB.getSelectedItem().toString());

            pst = con.prepareStatement("delete from employee_details where ID = ?");
            pst.setInt(1, id);

            int K = pst.executeUpdate();

            if (K == 1) {
                JOptionPane.showMessageDialog(this, "Record Deleted");

                EmployeeNameTXT.setText("");
                JobRoleTXT.setText("");
                DepartmentTXT.setText("");
                BasicSalaryTXT.setText("");
                AllowanceTXT.setText("");

                EmployeeNameTXT.requestFocus();

            } else {
                JOptionPane.showMessageDialog(this, "Record Not Deleted");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Delete Exception");
        }

    }//GEN-LAST:event_DeleteBTNActionPerformed

    private void SearchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBTNActionPerformed

        try {
            int id = Integer.parseInt(EmployeeIDCMB.getSelectedItem().toString());

            pst = con.prepareStatement("select * from employee_details where ID = ?");
            pst.setInt(1, id);
            rs = pst.executeQuery();

            if (rs.next() == true) {
                EmployeeNameTXT.setText(rs.getString(2));
                JobRoleTXT.setText(rs.getString(3));
                DepartmentTXT.setText(rs.getString(4));
                BasicSalaryTXT.setText(Integer.toString(rs.getInt(5)));
                AllowanceTXT.setText(Integer.toString(rs.getInt(6)));
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Search Not Successfull");
        }

    }//GEN-LAST:event_SearchBTNActionPerformed

    private void ClearBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBTNActionPerformed

        // Clear all employee detail fields
        EmployeeNameTXT.setText("");
        JobRoleTXT.setText("");
        DepartmentTXT.setText("");
        BasicSalaryTXT.setText("");
        AllowanceTXT.setText("");

// Cursor goes back to employee name field
        EmployeeNameTXT.requestFocus();

    }//GEN-LAST:event_ClearBTNActionPerformed

    private void BackBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBTNActionPerformed
// To close Employee Management page
        this.hide();

// To open main menu page again
        MainMenu Main = new MainMenu();
        Main.setVisible(true);
    }//GEN-LAST:event_BackBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AllowanceTXT;
    private javax.swing.JButton BackBTN;
    private javax.swing.JTextField BasicSalaryTXT;
    private javax.swing.JButton ClearBTN;
    private javax.swing.JButton DeleteBTN;
    private javax.swing.JTextField DepartmentTXT;
    private javax.swing.JComboBox<String> EmployeeIDCMB;
    private javax.swing.JTextField EmployeeNameTXT;
    private javax.swing.JButton InsertBTN;
    private javax.swing.JTextField JobRoleTXT;
    private javax.swing.JButton LogoutBTN;
    private javax.swing.JButton ManageEmployeesBTN;
    private javax.swing.JButton PayrollReportsBTN;
    private javax.swing.JButton PayslipManagementBTN;
    private javax.swing.JButton SalaryCalculationBTN;
    private javax.swing.JButton SearchBTN;
    private javax.swing.JButton UpdateBTN;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
