/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package payroll.management.system;

import java.sql.*;
//To make the java option work
import javax.swing.JOptionPane;

/**
 *
 * @author HP Elitebook 840 G8
 */
public class PayrollReports extends javax.swing.JFrame {

    /**
     * Creates new form PayrollReports
     */
    public PayrollReports() {
        initComponents();
        setLocationRelativeTo(null); //To center
        connect(); // Calling database connection code
    }

    // Global variables for database connection
    Connection con;
    PreparedStatement pst;
    ResultSet rs;

    public void connect() // method
    {
        // Database connection
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/payroll_system", "root", "");
            JOptionPane.showMessageDialog(null, "Connection Done");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No Connection");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        salary = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        DepartmentCMB = new javax.swing.JComboBox<>();
        jLabel42 = new javax.swing.JLabel();
        SalaryMonthTXT = new javax.swing.JTextField();
        GenerateReportBTN = new javax.swing.JButton();
        ClearBTN = new javax.swing.JButton();
        salary1 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        TotalEmployeesValueLBL = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        TotalBasicSalaryValueLBL = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        TotalAllowanceValueLBL = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        TotalNetSalaryValueLBL = new javax.swing.JLabel();
        salary2 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        TotalEPFValueLBL = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        TotalETFValueLBL = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        TotalTaxValueLBL = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        TotalLoanValueLBL = new javax.swing.JLabel();
        salary3 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        SelectedDepartmentValueLBL = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        DepartmentNetSalaryValueLBL = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        BackBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(0, 128, 0));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Payroll Reports");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(242, 242, 242))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(204, 255, 222));

        salary.setBackground(new java.awt.Color(22, 163, 74));

        jLabel41.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Select Department");

        jPanel22.setBackground(new java.awt.Color(0, 128, 0));

        jLabel44.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Report Filter");

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel44)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel44, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
        );

        DepartmentCMB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "HR", "Finance", "Operations", "IT", "Logistics", " " }));

        jLabel42.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Salary Month");

        GenerateReportBTN.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        GenerateReportBTN.setForeground(new java.awt.Color(0, 153, 51));
        GenerateReportBTN.setText("Generate Report");
        GenerateReportBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateReportBTNActionPerformed(evt);
            }
        });

        ClearBTN.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        ClearBTN.setForeground(new java.awt.Color(0, 153, 51));
        ClearBTN.setText("Clear");
        ClearBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout salaryLayout = new javax.swing.GroupLayout(salary);
        salary.setLayout(salaryLayout);
        salaryLayout.setHorizontalGroup(
            salaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, salaryLayout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addComponent(GenerateReportBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ClearBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(salaryLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(salaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel42)
                    .addComponent(jLabel41))
                .addGap(18, 18, 18)
                .addGroup(salaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DepartmentCMB, 0, 151, Short.MAX_VALUE)
                    .addComponent(SalaryMonthTXT))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        salaryLayout.setVerticalGroup(
            salaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salaryLayout.createSequentialGroup()
                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(salaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(DepartmentCMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(salaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(SalaryMonthTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(salaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenerateReportBTN)
                    .addComponent(ClearBTN))
                .addGap(47, 47, 47))
        );

        salary1.setBackground(new java.awt.Color(22, 163, 74));

        jPanel23.setBackground(new java.awt.Color(0, 128, 0));

        jLabel45.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Monthly Payroll Summary");

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel45)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel45, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
        );

        TotalEmployeesValueLBL.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        TotalEmployeesValueLBL.setForeground(new java.awt.Color(255, 255, 255));
        TotalEmployeesValueLBL.setText("XXXX");

        jLabel24.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Total Employees");

        TotalBasicSalaryValueLBL.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        TotalBasicSalaryValueLBL.setForeground(new java.awt.Color(255, 255, 255));
        TotalBasicSalaryValueLBL.setText("XXXX");

        jLabel25.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Total Basic Salary");

        jLabel26.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Total Allowances");

        TotalAllowanceValueLBL.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        TotalAllowanceValueLBL.setForeground(new java.awt.Color(255, 255, 255));
        TotalAllowanceValueLBL.setText("XXXX");

        jLabel27.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Total Net Salary");

        TotalNetSalaryValueLBL.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        TotalNetSalaryValueLBL.setForeground(new java.awt.Color(255, 255, 255));
        TotalNetSalaryValueLBL.setText("XXXX");

        javax.swing.GroupLayout salary1Layout = new javax.swing.GroupLayout(salary1);
        salary1.setLayout(salary1Layout);
        salary1Layout.setHorizontalGroup(
            salary1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(salary1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(salary1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jLabel27)
                    .addComponent(jLabel26)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(salary1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TotalBasicSalaryValueLBL)
                    .addComponent(TotalEmployeesValueLBL)
                    .addComponent(TotalAllowanceValueLBL)
                    .addComponent(TotalNetSalaryValueLBL))
                .addGap(47, 47, 47))
        );
        salary1Layout.setVerticalGroup(
            salary1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salary1Layout.createSequentialGroup()
                .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(salary1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(TotalEmployeesValueLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(salary1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(TotalBasicSalaryValueLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(salary1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(TotalAllowanceValueLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(salary1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(TotalNetSalaryValueLBL))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        salary2.setBackground(new java.awt.Color(22, 163, 74));

        jPanel24.setBackground(new java.awt.Color(0, 128, 0));

        jLabel46.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("Deduction Report");

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel46)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel46, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
        );

        TotalEPFValueLBL.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        TotalEPFValueLBL.setForeground(new java.awt.Color(255, 255, 255));
        TotalEPFValueLBL.setText("XXXX");

        jLabel28.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Total EPF");

        TotalETFValueLBL.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        TotalETFValueLBL.setForeground(new java.awt.Color(255, 255, 255));
        TotalETFValueLBL.setText("XXXX");

        jLabel29.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Total ETF");

        jLabel30.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Total Tax");

        TotalTaxValueLBL.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        TotalTaxValueLBL.setForeground(new java.awt.Color(255, 255, 255));
        TotalTaxValueLBL.setText("XXXX");

        jLabel31.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Total Loan");

        TotalLoanValueLBL.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        TotalLoanValueLBL.setForeground(new java.awt.Color(255, 255, 255));
        TotalLoanValueLBL.setText("XXXX");

        javax.swing.GroupLayout salary2Layout = new javax.swing.GroupLayout(salary2);
        salary2.setLayout(salary2Layout);
        salary2Layout.setHorizontalGroup(
            salary2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(salary2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(salary2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(jLabel28)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(salary2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, salary2Layout.createSequentialGroup()
                        .addComponent(TotalETFValueLBL)
                        .addGap(42, 42, 42))
                    .addGroup(salary2Layout.createSequentialGroup()
                        .addGroup(salary2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TotalEPFValueLBL)
                            .addComponent(TotalTaxValueLBL)
                            .addComponent(TotalLoanValueLBL))
                        .addContainerGap())))
        );
        salary2Layout.setVerticalGroup(
            salary2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salary2Layout.createSequentialGroup()
                .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(salary2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(TotalEPFValueLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(salary2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(TotalETFValueLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(salary2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(TotalTaxValueLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(salary2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(TotalLoanValueLBL))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        salary3.setBackground(new java.awt.Color(22, 163, 74));

        jPanel25.setBackground(new java.awt.Color(0, 128, 0));

        jLabel47.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("Department Report");

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel47)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel47, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
        );

        SelectedDepartmentValueLBL.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        SelectedDepartmentValueLBL.setForeground(new java.awt.Color(255, 255, 255));
        SelectedDepartmentValueLBL.setText("XXXX");

        jLabel32.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Selected Department");

        DepartmentNetSalaryValueLBL.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        DepartmentNetSalaryValueLBL.setForeground(new java.awt.Color(255, 255, 255));
        DepartmentNetSalaryValueLBL.setText("XXXX");

        jLabel33.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Department Net Salary");

        javax.swing.GroupLayout salary3Layout = new javax.swing.GroupLayout(salary3);
        salary3.setLayout(salary3Layout);
        salary3Layout.setHorizontalGroup(
            salary3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(salary3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(salary3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(salary3Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(DepartmentNetSalaryValueLBL))
                    .addGroup(salary3Layout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SelectedDepartmentValueLBL)))
                .addGap(24, 24, 24))
        );
        salary3Layout.setVerticalGroup(
            salary3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salary3Layout.createSequentialGroup()
                .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(salary3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(SelectedDepartmentValueLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(salary3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(DepartmentNetSalaryValueLBL))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        BackBTN.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        BackBTN.setForeground(new java.awt.Color(204, 51, 0));
        BackBTN.setText("Back");
        BackBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(576, 576, 576)
                        .addComponent(BackBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(salary1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(salary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(salary3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(salary2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(BackBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(salary, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(salary3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(salary1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(salary2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClearBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBTNActionPerformed

        // Clear report display values
        SalaryMonthTXT.setText("");

        TotalEmployeesValueLBL.setText("XXXX");
        TotalBasicSalaryValueLBL.setText("XXXX");
        TotalAllowanceValueLBL.setText("XXXX");
        TotalNetSalaryValueLBL.setText("XXXX");

        TotalEPFValueLBL.setText("XXXX");
        TotalETFValueLBL.setText("XXXX");
        TotalTaxValueLBL.setText("XXXX");
        TotalLoanValueLBL.setText("XXXX");

        SelectedDepartmentValueLBL.setText("XXXX");
        DepartmentNetSalaryValueLBL.setText("XXXX");

    }//GEN-LAST:event_ClearBTNActionPerformed

    private void BackBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBTNActionPerformed

        // To close payroll reports page
        this.hide();

// To open main menu page again
        MainMenu Main = new MainMenu();
        Main.setVisible(true);

    }//GEN-LAST:event_BackBTNActionPerformed

    private void GenerateReportBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateReportBTNActionPerformed

        try {
            String department = DepartmentCMB.getSelectedItem().toString();

            // Generate report for all departments
            if (department.equals("All")) {

                pst = con.prepareStatement("select count(Employee_ID), sum(Basic_Salary), sum(Allowance), "
                        + "sum(Net_Salary), sum(EPF), sum(ETF), sum(Tax), sum(Loan) from salary_details");
                rs = pst.executeQuery();

                if (rs.next() == true) {
                    TotalEmployeesValueLBL.setText(Integer.toString(rs.getInt(1)));
                    TotalBasicSalaryValueLBL.setText(Integer.toString(rs.getInt(2)));
                    TotalAllowanceValueLBL.setText(Integer.toString(rs.getInt(3)));
                    TotalNetSalaryValueLBL.setText(Integer.toString(rs.getInt(4)));

                    TotalEPFValueLBL.setText(Integer.toString(rs.getInt(5)));
                    TotalETFValueLBL.setText(Integer.toString(rs.getInt(6)));
                    TotalTaxValueLBL.setText(Integer.toString(rs.getInt(7)));
                    TotalLoanValueLBL.setText(Integer.toString(rs.getInt(8)));

                    SelectedDepartmentValueLBL.setText("All");
                    DepartmentNetSalaryValueLBL.setText(Integer.toString(rs.getInt(4)));
                }

            } else {

                // Generate report for selected department
                pst = con.prepareStatement("select count(Employee_ID), sum(Basic_Salary), sum(Allowance), "
                        + "sum(Net_Salary), sum(EPF), sum(ETF), sum(Tax), sum(Loan) from salary_details where Department = ?");
                pst.setString(1, department);
                rs = pst.executeQuery();

                if (rs.next() == true) {
                    TotalEmployeesValueLBL.setText(Integer.toString(rs.getInt(1)));
                    TotalBasicSalaryValueLBL.setText(Integer.toString(rs.getInt(2)));
                    TotalAllowanceValueLBL.setText(Integer.toString(rs.getInt(3)));
                    TotalNetSalaryValueLBL.setText(Integer.toString(rs.getInt(4)));

                    TotalEPFValueLBL.setText(Integer.toString(rs.getInt(5)));
                    TotalETFValueLBL.setText(Integer.toString(rs.getInt(6)));
                    TotalTaxValueLBL.setText(Integer.toString(rs.getInt(7)));
                    TotalLoanValueLBL.setText(Integer.toString(rs.getInt(8)));

                    SelectedDepartmentValueLBL.setText(department);
                    DepartmentNetSalaryValueLBL.setText(Integer.toString(rs.getInt(4)));
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Report Not Generated");
        }

    }//GEN-LAST:event_GenerateReportBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PayrollReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PayrollReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PayrollReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PayrollReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PayrollReports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBTN;
    private javax.swing.JButton ClearBTN;
    private javax.swing.JComboBox<String> DepartmentCMB;
    private javax.swing.JLabel DepartmentNetSalaryValueLBL;
    private javax.swing.JButton GenerateReportBTN;
    private javax.swing.JTextField SalaryMonthTXT;
    private javax.swing.JLabel SelectedDepartmentValueLBL;
    private javax.swing.JLabel TotalAllowanceValueLBL;
    private javax.swing.JLabel TotalBasicSalaryValueLBL;
    private javax.swing.JLabel TotalEPFValueLBL;
    private javax.swing.JLabel TotalETFValueLBL;
    private javax.swing.JLabel TotalEmployeesValueLBL;
    private javax.swing.JLabel TotalLoanValueLBL;
    private javax.swing.JLabel TotalNetSalaryValueLBL;
    private javax.swing.JLabel TotalTaxValueLBL;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel salary;
    private javax.swing.JPanel salary1;
    private javax.swing.JPanel salary2;
    private javax.swing.JPanel salary3;
    // End of variables declaration//GEN-END:variables
}
